package com.semartinez.projects.choppit.controller.exception;


/**
 * ConnectionFailureException handles errors thrown by {@link com.semartinez.projects.choppit.model.repository.RecipeRepository#connect(String)},
 * which are generated by {@link org.jsoup.Jsoup#connect(String)}
 */
public class ConnectionFailureException extends RuntimeException {

  /**
   * @param s describes the specific failure that occurred connecting to the user-supplied URL.
   */
  public ConnectionFailureException(String s) {
    super(s);
  }
}
